function graficaDatos(YMatrix1)
%CREATEFIGURE2(YMatrix1)
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 01-Nov-2022 13:29:20

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to semilogy
semilogy1 = semilogy(YMatrix1,'Parent',axes1);
set(semilogy1(1),'DisplayName','I - Oficial','LineWidth',1);
set(semilogy1(2),'DisplayName','R - Oficial','LineWidth',1);
set(semilogy1(3),'DisplayName','F - Oficial','LineWidth',2,'LineStyle','--',...
    'Color',[0 0 1]);
set(semilogy1(4),'DisplayName','U - Oficial hospitalized');
set(semilogy1(5),'DisplayName','I - smooth','LineWidth',3,'LineStyle',':',...
    'Color',[0 0 0]);
set(semilogy1(6),'DisplayName','R- movil smooth','LineWidth',2,...
    'Color',[0 0 0]);
set(semilogy1(7),'DisplayName','F - movil smooth','LineWidth',3,...
    'LineStyle','--',...
    'Color',[0 0 0]);
set(semilogy1(8),'DisplayName','UCI hospitalized','LineWidth',3,...
    'LineStyle','-.',...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);
set(semilogy1(9),'DisplayName','Deaths confirmed covid','LineWidth',2,...
    'Color',[1 0 0]);
set(semilogy1(10),'DisplayName','UCI input daily',...
    'MarkerFaceColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'MarkerEdgeColor',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'MarkerSize',2,...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 14]);
box(axes1,'on');
hold(axes1,'off');
set(axes1,'YMinorTick','on','YScale','log');
% Create legend
legend(axes1,'show');

