function acumDis(YMatrix1)
%CREATEFIGURE2(YMatrix1)
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 22-Nov-2022 11:18:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Infected','Color',[0 0 1],'LineWidth',1);
set(plot1(2),'DisplayName','Recovered',...
    'Color',[0.600000023841858 0.200000002980232 0],'LineWidth',1);
set(plot1(3),'DisplayName','Deceased','Color',[1 0 0],'LineWidth',1);
set(plot1(4),'DisplayName','ICU Internships','LineWidth',1,'LineStyle','--',...
    'Color',[0 0 0]);
set(plot1(5),'DisplayName','ICU admission','Color',[0 0 0],'LineWidth',1);

% Create ylabel
ylabel('cumulative case incidence');

% Create xlabel
xlabel('TIme (days)');

% Create title
title('National epidemiological curves (Chile)');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.160733789534874 0.672297953872706 0.197560971575539 0.170769225955009],...
    'FontSize',12);

