function [CamasHospitalDiarioT,basica,media,uti,uci] = loadDataProducto24(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CAMASHOSPITALDIARIOT = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CAMASHOSPITALDIARIOT = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CamasHospitalDiarioT = importfile(".\producto24\CamasHospital_Diario_T.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Oct-2022 18:11:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TipoDeCama", "Basica", "Media", "UTI", "UCI"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TipoDeCama", "InputFormat", "yyyy-MM-dd");

% Import the data
CamasHospitalDiarioT = readtable(filename, opts);
basica = CamasHospitalDiarioT.Basica;
media = CamasHospitalDiarioT.Media;
uti = CamasHospitalDiarioT.UTI;
uci = CamasHospitalDiarioT.UCI;
end