function CasosConfirmadostotalRegional = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CASOSCONFIRMADOSTOTALREGIONAL = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  CASOSCONFIRMADOSTOTALREGIONAL = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CasosConfirmadostotalRegional = importfile("R:\2022\covid-dev\GSM-covid19CL\GSM-covid19CL\dataCL\producto4\2022-03-21-CasosConfirmados-totalRegional.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Nov-2022 11:36:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Region", "CasosTotalesAcumulados", "FallecidosConfirmadosTotales", "FallecidosSospechososProbablesUOtrosTotales", "FallecidosTotales", "CasosConfirmadosRecuperados", "CasosConfirmadosPorAntigeno", "CasosConSospechaDeReinfeccion", "CasosProbablesAcumulados", "CasosActivosProbables", "CasosNuevosTotales", "CasosNuevosConSintomas", "CasosNuevosSinSintomas", "CasosNuevosReportadosPorLaboratorio", "CasosNuevosConfirmadosPorAntigeno", "CasosActivosConfirmados"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Region", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Region", "EmptyFieldRule", "auto");

% Import the data
CasosConfirmadostotalRegional = readtable(filename, opts);

end