function incidenciaenvacunados = loadDataProducto90(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INCIDENCIAENVACUNADOS = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  INCIDENCIAENVACUNADOS = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  incidenciaenvacunados = importfile("R:\2022\covid-dev\GSM-covid19CL\GSM-covid19CL\dataCL\producto90\incidencia_en_vacunados.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Jan-2023 20:41:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["semana_epidemiologica", "sin_vac_casos", "una_dosis_casos", "dos_dosis_casos", "dos_dosis_comp_casos", "dosis_unica_casos", "dosis_unica_comp_casos", "dosis_ref_comp_casos", "sin_vac_uci", "una_dosis_uci", "dos_dosis_uci", "dos_dosis_comp_uci", "dosis_unica_uci", "dosis_unica_comp_uci", "dosis_ref_comp_uci", "sin_vac_fall", "una_dosis_fall", "dos_dosis_fall", "dos_dosis_comp_fall", "dosis_unica_fall", "dosis_unica_comp_fall", "dosis_ref_comp_fall", "personas_con_una_dosis", "personas_con_pauta_completa", "personas_con_refuerzo"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "semana_epidemiologica", "TrimNonNumeric", true);
opts = setvaropts(opts, "semana_epidemiologica", "ThousandsSeparator", ",");

% Import the data
incidenciaenvacunados = readtable(filename, opts);

end