function IngresosUCIt = importP91(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INGRESOSUCIT = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  INGRESOSUCIT = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  IngresosUCIt = importfile("R:\2022\covid-seir-delay-main-09-2021\covid-seir-delay-main\data\producto91\Ingresos_UCI_t.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Sep-2022 15:45:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Serie", "MediaMvilIngresosAUCIPorCOVID19"];
opts.VariableTypes = ["datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Serie", "InputFormat", "yyyy-MM-dd");

% Import the data
IngresosUCIt = readtable(filename, opts);

end