function [covid19chile,I,R,F,U,T,IC,RC,FC] = loadDataIvanGit(region,grafica,pathDATA,globalPais)
%global globalUCImovil
%IMPORTFILE Import data from a text file
% https://github.com/ivanMSC/COVID19_Chile
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jan-2022 15:22:00

%% Input handling
% I=0;
% R=0;
% F=0;
% U=0;
% If dataLines is not specified, define defaults
%if nargin < 2
dataLines = [2, Inf];



%end
filename = strcat(pathDATA,'\git-ivanMSC\Covid19_chile.csv')
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Fecha", "Region", "NuevoConfirmado", "NuevoMuerte", "NuevoRecuperado", "AcumConfirmado", "AcumMuerte", "AcumRecuperado", "CasosUCI"];
opts.VariableTypes = ["categorical", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Fecha", "Region"], "EmptyFieldRule", "auto");

% Import the data
covid19chile = readtable(filename, opts);

[f,c] = size(covid19chile)
if globalPais==1  
    salto=17; % regiones + no informado
    inicio=1;
    sz = [f/salto c];
    VariableNames0 = {'Fecha', 'Region', 'NuevoConfirmado', 'NuevoMuerte', 'NuevoRecuperado', 'AcumConfirmado', 'AcumMuerte', 'AcumRecuperado', 'CasosUCI'};
    VariableTypes0 = {'categorical', 'categorical', 'double', 'double', 'double', 'double', 'double', 'double', 'double'};
    tmpTable = table('size',sz,'VariableTypes',VariableTypes0,'VariableNames',VariableNames0);
    for i=1:f/salto
        a=inicio;
        b=inicio+salto-1;
        A = table2array(covid19chile(a:b,3:end));
        values = sum(A,'omitnan');
        inicio=inicio+salto;
        variable = covid19chile.Fecha(a);
        tmpTable(i,1:end) = {variable,'Chile',values(1,1),values(1,2),values(1,3),values(1,4),values(1,5),values(1,6),values(1,7)};
    end
dataTable = tmpTable;
else
dataTable = covid19chile(string(covid19chile.Region)==region, :);
end

T = dataTable(:,:); % Tabla completa
dataTableDouble = dataTable(:,3:end);
I = table2array(dataTableDouble(:,1))';% Casos Infectados
F = table2array(dataTableDouble(:,2))';% Casos Fallecidos
R = table2array(dataTableDouble(:,3))';% Casos Recuperados
IC = table2array(dataTableDouble(:,4))';% Casos Infectados
FC = table2array(dataTableDouble(:,5))';% Casos Fallecidos
RC = table2array(dataTableDouble(:,6))';% Casos Recuperados
U = table2array(dataTableDouble(:,7))';% Casos UCI

end