function createfigure1(YMatrix1)
%CREATEFIGURE1(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Nov-2021 19:44:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Arica');
set(plot1(2),'DisplayName','Atacama');
set(plot1(3),'DisplayName','Ant');
set(plot1(4),'DisplayName','Tar');
set(plot1(5),'DisplayName','Coq');
set(plot1(6),'DisplayName','Valp');
set(plot1(7),'DisplayName','Maule');
set(plot1(8),'DisplayName','Ñuble');
set(plot1(9),'DisplayName','BioBio');
set(plot1(10),'DisplayName','Araucanía');
set(plot1(11),'DisplayName','Los Ríos');
set(plot1(12),'DisplayName','Los Lagos');
set(plot1(13),'DisplayName','Aysén');
set(plot1(14),'DisplayName','Magallanes');
set(plot1(15),'DisplayName','Metropolitana');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

